import type { State, Project, Strategy, Asset, Publication, Insight, ContentRule } from '../src/types';
import type { ZodType } from 'zod';
export const id: () => string;
export const now: () => string;
export const categories: [string, ...string[]];
export const briefSchema: ZodType<Project['brief']>;
export function assert(value: unknown, message: string, status?: number): asserts value;
export function seedState(): State;
export function newProject(input: unknown): Project;
export function touch(project: Project): void;
export function activity(state: State, title: string, detail: string, projectId: string): void;
export function makeDraft(project: Project, changes?: Record<string, unknown>, instruction?: string, source?: string, rules?: ContentRule[], query?: string): Strategy;
export function editStrategy(project: Project, id: string, input: unknown, rules?: ContentRule[]): Strategy;
export function confirmStrategy(project: Project, id: string, rules?: ContentRule[]): Strategy;
export function updateAsset(project: Project, id: string, input: unknown, rules?: ContentRule[]): Asset;
export function schedulePublication(project: Project, accounts: State['accounts'], input: unknown): Publication;
export function confirmPublication(project: Project, id: string, input: unknown): Publication;
export function importComments(project: Project, input: unknown): { added: number; duplicates: number };
export function analyzeComments(project: Project): Insight[];
export function decideInsight(project: Project, id: string, input: unknown): Insight;
