import { useEffect, useState } from 'react';
import { ArrowRight, Eye, EyeOff, Leaf, Loader2, LockKeyhole, Sprout } from 'lucide-react';
import App from './App';
import { localUsername, lockLocalWorkspace, loginLocal, registerLocal } from './local-vault';
import './local-auth.css';
import { IS_WEB } from './api';

type Backend = { username: string; authenticate: (mode: 'login' | 'register', username: string, password: string, remember?: boolean) => Promise<string>; logout: () => Promise<void>; remembered: { id: string; username: string }[]; rememberSupported: boolean; quick: (id: string) => Promise<string>; forget: (id: string) => Promise<void> };
export default function LocalAuth({ backend }: { backend?: Backend } = {}) {
  const [user, setUser] = useState(localUsername); const [mode, setMode] = useState<'login' | 'register'>('login');
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState('');
  const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [remember, setRemember] = useState(false);
  useEffect(() => { const locked = () => { setUser(''); setPassword(''); setConfirmation(''); }; window.addEventListener('studio-local-locked', locked); return () => window.removeEventListener('studio-local-locked', locked); }, []);
  const activeUser = backend ? backend.username : user;
  useEffect(() => { if (activeUser) { setMode('login'); setRemember(false); } }, [activeUser]);
  if (activeUser) return <App key={activeUser} localUser={activeUser} onLocalLogout={backend ? backend.logout : lockLocalWorkspace}/>;
  const switchMode = (next: typeof mode) => { setMode(next); setPassword(''); setConfirmation(''); setError(''); };
  return <div className="local-auth"><section className="auth-story"><a className="auth-brand" href="#dashboard"><span className="brand-mark"><Sprout size={27}/></span>生长<span>.</span></a><div className="auth-story-copy"><span className="auth-eyebrow">YOUR IDEAS, GROWING.</span><h1>好想法，<br/>在这里生长。</h1><p>从品牌的第一份策略，<br/>到下一次被看见的内容。</p><div className="auth-orbit" aria-hidden="true"><span>✳</span><i/><b><Leaf size={19}/>每一次创作，都是积累。</b></div></div><small>生长 STUDIO · 个人创作工作台</small></section><section className="auth-form-side"><div className="auth-card"><span className="auth-label"><LockKeyhole size={15}/>你的设备 · 你的工作区</span><h2>{mode === 'login' ? '欢迎回来。' : '从一个新想法开始。'}</h2><p className="auth-intro">{mode === 'login' ? (backend && !IS_WEB ? '登录这台电脑中的个人工作区。' : '登录这个浏览器中的个人工作区。') : '创建本地用户，开启独立的创作空间。'}</p><div className="auth-tabs" role="tablist" aria-label="登录方式"><button role="tab" aria-selected={mode === 'login'} onClick={() => switchMode('login')} disabled={busy}>登录</button><button role="tab" aria-selected={mode === 'register'} onClick={() => switchMode('register')} disabled={busy}>注册本地用户</button></div><form onSubmit={async e => { e.preventDefault(); setError(''); if (busy) return; if (mode === 'register' && password !== confirmation) { setError('两次输入的密码不一致。'); return; } setBusy(true); try { const name = backend ? await backend.authenticate(mode, username, password, remember) : await (mode === 'login' ? loginLocal : registerLocal)(username, password); setPassword(''); setConfirmation(''); setUser(name); } catch (e) { setError(e instanceof Error ? e.message : '暂时无法打开工作区，请重试。'); } finally { setBusy(false); } }}>
      <label className="field"><span>用户名</span><input required minLength={2} maxLength={32} autoComplete="username" autoCapitalize="none" spellCheck={false} placeholder="例如：小野" value={username} disabled={busy} onChange={e => setUsername(e.target.value)}/></label>
      <label className="field"><span>密码</span><div className="auth-password"><input required minLength={mode === 'register' ? 10 : 1} maxLength={128} type={visible ? 'text' : 'password'} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} placeholder={mode === 'register' ? '至少 10 位，用于加密本地数据' : '输入你的本地登录密码'} value={password} disabled={busy} onChange={e => setPassword(e.target.value)}/><button type="button" className="icon-button" aria-label={visible ? '隐藏密码' : '显示密码'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div></label>
      {mode === 'register' && <label className="field"><span>确认密码</span><input required minLength={10} maxLength={128} type="password" autoComplete="new-password" placeholder="再次输入密码" value={confirmation} disabled={busy} onChange={e => setConfirmation(e.target.value)}/></label>}
      {backend?.rememberSupported && <label className="checkbox-row remember-login"><input type="checkbox" checked={remember} onChange={e => setRemember(e.target.checked)} disabled={busy}/><span>自动登录 · 下次点击用户名即可进入</span></label>}
      {remember && <p className="small-note">{IS_WEB ? '使用此浏览器的人可点击用户名进入。浏览器保存不可导出的解锁密钥，不保存明文密码。公共设备请勿勾选；可在用户名旁取消记住。' : '此 Windows 账户的使用者可直接打开被记住的工作区；解锁凭据由 Windows 加密保护，不保存明文密码。可在用户名卡片旁取消记住。'}</p>}
      {backend && mode === 'login' && backend.remembered.length > 0 && <section className="remembered-users" aria-label="已记住的用户"><p>点击用户名，直接进入</p>{backend.remembered.map(saved => <div key={saved.id} className="remembered-user"><button type="button" disabled={busy} className="remembered-name" onClick={async () => { setBusy(true); setError(''); try { setUser(await backend.quick(saved.id)); setPassword(''); } catch (error) { setError(error instanceof Error ? error.message : '请使用密码登录'); setUsername(saved.username); } finally { setBusy(false); } }}><span>{saved.username.slice(0, 1)}</span><b>{saved.username}</b><ArrowRight size={17}/></button><button type="button" className="text-button" disabled={busy} aria-label={`取消记住 ${saved.username}`} onClick={async () => { setBusy(true); try { await backend.forget(saved.id); } catch (error) { setError(error instanceof Error ? error.message : '操作失败'); } finally { setBusy(false); } }}>取消记住</button></div>)}</section>}
      {error && <p className="auth-error" role="alert">{error}</p>}
      <button className="button primary auth-submit" disabled={busy}>{busy ? <><Loader2 size={17} className="spin"/>正在打开工作区…</> : <>{mode === 'login' ? '进入我的工作区' : '创建并进入工作区'}<ArrowRight size={17}/></>}</button>
    </form><div className="auth-privacy"><LockKeyhole size={18}/><p>{IS_WEB ? '账号、项目和 API 密钥由登录密码加密，只保存在当前浏览器。联网请求临时经过网站后端，相关内容发送至你选择的服务商；网站后端不保存这些数据。' : backend ? '项目和素材加密保存在这台电脑，不同用户分别保存。API 密钥由登录密码和 Windows 账户共同保护。' : '数据由密码加密，只保存在当前浏览器。不同用户各自保存，退出后需重新登录。'}<br/><strong>{IS_WEB ? '不同设备不自动同步；密码无法找回。清除浏览器数据会删除工作区。自动任务需保持网页打开。' : backend ? '请牢记密码；退出最后一个会话后，本账号的后台任务会暂停。' : '密码无法找回；清除浏览器数据会删除工作区。'}</strong></p></div><p className="auth-static-note">{IS_WEB ? '联网网页版 · 本地加密工作区 · 登录后配置 AI 与平台连接' : backend ? 'Windows 完整版 · 登录后可配置 AI 与平台连接' : <a href="https://github.com/JerryCoal/shengzhang-studio/releases/latest" target="_blank" rel="noreferrer">下载 Windows 完整版，使用 AI 与平台连接 ↗</a>}</p></div></section></div>;
}
